### ISSUE TITLE
Countdown Timers

### ISSUE THREAD

**Issue by dakkiboy17** [rpfilomeno/hmr-main#102]
![image](https://user-images.githubusercontent.com/28706075/29347278-13f4572a-827e-11e7-8380-0a2589315583.png)

![image](https://user-images.githubusercontent.com/28706075/29347293-37461628-827e-11e7-9a16-b02a7c965e0a.png)

If the auction started
Ends

if the auction is upcoming
Starts

**Comment by rpfilomeno** [comment]
not on theme
