### ISSUE TITLE
Auction Maintenance - Retrieval of images and thumbnails should be optimize

### ISSUE THREAD

**Issue by dakkiboy17** [rpfilomeno/hmr-main#35]
Retrieval of images and thumbnails should be optimize by retrieve only images of SHOWN lots or items.
Currently retrieving all images of all the lots and items that causes the page not to load.

**Comment by dakkiboy17** [comment]
Or create a separate retrieval of the images and let the whole page load first.

**Comment by rpfilomeno** [comment]
Hmm. Images are loaded through html tag via image servelet. So no image query unless html is asking to serve it. Its not queried on call at bid servelet.

Possible fix is lazy load jquery but i doubt its a major improvement. Possible it needs db and tomcat optimization if image loading from db chokes. Also have the images cached through cloudflare. Lets discuss tom?

**Comment by dakkiboy17** [comment]
Lazy loading should be done as we are loading a number of items.
