### ISSUE TITLE
Bidding : Cannot BID anymore for the item once you are the highest bidder

### ISSUE THREAD

**Issue by dakkiboy17** [rpfilomeno/hmr-main#38]
If the Bidder is currently the hight bidder for the lot, he cannot BID anymore and will see a button YOUR BID instead of BID <Amount>.

**Comment by rpfilomeno** [comment]
i asked this before and said it was allowed so you can push up the bid higher?

**Comment by dakkiboy17** [comment]
As per hmr bidding rules. Once you are the current highest bidder, you have to give chance to other bidder
