### ISSUE TITLE
Auction Setup : Once Auction Type = Negotiated and Qualifier Price is not Empty

### ISSUE THREAD

**Issue by dakkiboy17** [rpfilomeno/hmr-main#40]
Once Auction Type = Negotiated and Qualifier Price is not empty, or set to target price, SRP, depending on the selection.

Set all Lot Buy Price = Lot <selected Price>

**Comment by rpfilomeno** [comment]
what is the db field? Give example.

**Comment by dakkiboy17** [comment]
On Auction Setup
If
Auction Type = Negotiated
and
bid_qualifier_price!=null or has value

LOT
if(bid_qualifier_price=SRP)
buy_price = srp_total
if(bid_qualifier_price=Target)
buy_price = target_price_total
if(bid_qualifier_price=Reserve)
buy_price = reserve_price_total
if(bid_qualifier_price=Assessment)
buy_price = assess_value_total

**Comment by rpfilomeno** [comment]
what is SRP,  Target, Reserve and Assessment where are the other values coming from?

**Comment by rpfilomeno** [comment]
When do i update the lot.buy_price? on create? on update? Then this should be a db trigger right on update and insert?

**Comment by dakkiboy17** [comment]
fixed. Done
