### ISSUE TITLE
BIDDING : if Lot is available lot, Display the quantity and remaining on the side

### ISSUE THREAD

**Issue by dakkiboy17** [rpfilomeno/hmr-main#42]
Also on the pop ups, display the quantity before before confirm

**Comment by rpfilomeno** [comment]
Explain "remaining" coz until bid is awarded, we dont know whats remaining

**Comment by dakkiboy17** [comment]
Example :

Available Lot = 1

Lot No : 1

Quantity = 10


1. Bidder 100 Bid 1000php for 1 pc. = total 1000

2. Bidder 123 Bid 1100php for 3 pc. = total 3000

3. Bidder 111 Bid 1200php for 1 pc. = total 1000

4. Auction Closes

The winner is Bidder 111 for 1pc total 1000



HMR will do a backend process of calling the other bidders asking them to
buy it at their price. Depending on HMR

**Comment by rpfilomeno** [comment]
so the bid is per piece not the entire quantity?

**Comment by dakkiboy17** [comment]
No. Bid is per piece still but to make sure that the highest bidder is really the winner. Even having one item as long as higher than other bidder who has many item number or count. the highest bidder should be prioritize.
