### ISSUE TITLE
Bidding - agree on terms and conditions date should be saved on a particular auction

### ISSUE THREAD

**Issue by dakkiboy17** [rpfilomeno/hmr-main#43]
Save the date of clicking on the agree on terms and conditions per Auction.

**Comment by rpfilomeno** [comment]
which page is this visible and what table/field to update?

**Comment by dakkiboy17** [comment]
auction user bidder table. Terms and condition field. On press of bid or buy or make offer button. The first time pressing. Mandate ito ng audit

**Comment by dakkiboy17** [comment]
Incase kasi ayaw sumunod

**Comment by dakkiboy17** [comment]
Ilagay nalang natin sya sa are you sure? May additional note na you are agreeing on term and condition

**Comment by dakkiboy17** [comment]
Wala ng additional notes. 
Mailog lang natin at sa next bidding on that auction... wag na lumabas yung pop up.

**Comment by dakkiboy17** [comment]
Pero dapat sa pop up lumabas na by reading this you are agreeing on the terms and conditions..
Something to that effect on bidders first bidding on that auction

**Comment by rpfilomeno** [comment]
As discussed it will just be added on popup if user's first time to bid under an auction
