### ISSUE TITLE
Lot : Image Gallery does not contain the Lot Image

### ISSUE THREAD

**Issue by dakkiboy17** [rpfilomeno/hmr-main#48]
Lot : Image Gallery does not contain the Lot Image
Item: Image Gallery does not contain the Item Image

**Comment by rpfilomeno** [comment]
Pls confirm image was saved on db. Work on my end

**Comment by rpfilomeno** [comment]
Please screenshot

**Comment by dakkiboy17** [comment]
[image: Inline image 1]


[image: Inline image 2]


[image: Inline image 3]

**Comment by dakkiboy17** [comment]
Sa Admin module, na Lot Images, tsaka sa display sa main page at bidding page.

Wala yung image

**Comment by rpfilomeno** [comment]
This is db server problem, set:
max_allowed_packet = 16M
innodb_log_file_size = 256M
