### ISSUE TITLE
Auction : Uploading of Images 

### ISSUE THREAD

**Issue by dakkiboy17** [rpfilomeno/hmr-main#60]
When there are more than 1 image upload 
Example 1,2,3,4,5 jpg...
Not all images are uploaded.

Front end error 

![image](https://user-images.githubusercontent.com/28706075/28904675-37aef5ce-783f-11e7-8c9a-4361b0377301.png)

And also...

two images are only process.

I have to click upload button again to process the next 2...

and so on.

**Comment by rpfilomeno** [comment]
db connection problem to

**Comment by dakkiboy17** [comment]
ok tol. cge. ako na d2.
