### ISSUE TITLE
Bidding and Index Pages and Lot Pages : Display of images not showing the image

### ISSUE THREAD

**Issue by dakkiboy17** [rpfilomeno/hmr-main#61]
![image](https://user-images.githubusercontent.com/28706075/28904767-ce72337c-783f-11e7-9e9c-b1bb7ec88dec.png)

Auction Bidding 

![image](https://user-images.githubusercontent.com/28706075/28904776-db098676-783f-11e7-98da-66614d301170.png)

**Comment by rpfilomeno** [comment]
Fixed
