### ISSUE TITLE
Private Bidding : Emails on Invite : HMR Admin accepted Yes 

### ISSUE THREAD

**Issue by dakkiboy17** [rpfilomeno/hmr-main#63]
HMR Admin and Private user should be able to accept emails that HMR Admin clicked Yes

**Comment by rpfilomeno** [comment]
Which form? Screenshot it

**Comment by dakkiboy17** [comment]
Yung may Yes No na button sa acceptance of bidding on Private Bidding yung may Invite link.

**Comment by dakkiboy17** [comment]
closed
