### ISSUE TITLE
Watch List : Bidders can tag a lot for watchlist and see all his watchlist in My Watchlist

### ISSUE THREAD

**Issue by dakkiboy17** [rpfilomeno/hmr-main#67]
auction_user_watchlist table

**Comment by rpfilomeno** [comment]
how to add to watch list?

**Comment by dakkiboy17** [comment]
Button nalang or isang image na mata sa Lot level upon bidding.
![image](https://user-images.githubusercontent.com/28706075/28999614-37a4ba36-7a7f-11e7-9455-a164d999e8c6.png)
