### ISSUE TITLE
Auction is Already Closed and Completed

### ISSUE THREAD

**Issue by dakkiboy17** [rpfilomeno/hmr-main#68]
When auction is closed and ended. It should show whether an item is sold.
Remarks "Sold" should be placed in the Lot display

When auction has bid qualifier price selected example SRP or Target or reserve or Assess.
And the Bid Amount is lower than the selected qualifier price...
Remarks "No Sale" should be placed in the Lot display

**Comment by rpfilomeno** [comment]
how do you know which which is selected? the bid is always the value of bid amount, how can that be lower than whats required to win?

**Comment by dakkiboy17** [comment]
For the Bidding with no Qualifier, all lots with bidding transactions are considered sold when the status of the auction is closed and ended.

For the Bidding with Qualifier, all lots with bidding transactions are considered below and when the status of the auction is closed and ended.
Chosen Qualifier = SRP = 100
1. Sold = Bid = 190
2. No Sale = Bid = 90

**Comment by rpfilomeno** [comment]
Add ka nalang field to indicate this, hindi ko maintindihan logic, i just need to display something based on field.
