### ISSUE TITLE
Bidding : Main Auction Image Does not show

### ISSUE THREAD

**Issue by dakkiboy17** [rpfilomeno/hmr-main#75]
![image](https://user-images.githubusercontent.com/28706075/29000533-b71de528-7aa0-11e7-9418-87a42c8ebc79.png)

**Comment by dakkiboy17** [comment]
Closed. Adjusted

**Comment by rpfilomeno** [comment]
Reverted. Your code creates double image:
![image](https://user-images.githubusercontent.com/5754735/29007357-ec3c222c-7b33-11e7-91f8-7bc473ac31b4.png)
