### ISSUE TITLE
No login in Mobile view responsive

### ISSUE THREAD

**Issue by dakkiboy17** [rpfilomeno/hmr-main#80]
![image](https://user-images.githubusercontent.com/28706075/29174264-5ac66892-7e18-11e7-9a56-12ba7d46401d.png)

**Comment by rpfilomeno** [comment]
![image](https://user-images.githubusercontent.com/5754735/29226507-e86530ec-7f04-11e7-9d1b-c33f94f7a7d6.png)

Touch top right 3-line icon
