### ISSUE TITLE
Top Menu : Welcome My Name <-- Name not My Account 

### ISSUE THREAD

**Issue by dakkiboy17** [rpfilomeno/hmr-main#97]

**Comment by rpfilomeno** [comment]
No, coz it will break the layout if you have a long name.

On desktop:

![image](https://user-images.githubusercontent.com/5754735/29268232-855c13dc-811e-11e7-81a7-fd048934b53f.png)

On Mobile:
![image](https://user-images.githubusercontent.com/5754735/29268317-d8147ab0-811e-11e7-985f-b47589d86c27.png)
