### ISSUE TITLE
profile should be 2010 : Edit profile only shows 1960 

### ISSUE THREAD

**Issue by dakkiboy17** [rpfilomeno/hmr-main#98]
Address should be updated.

* ID might require for pullout of items

**Comment by rpfilomeno** [comment]
MIN: 1907

![image](https://user-images.githubusercontent.com/5754735/29268085-f1a1bbce-811d-11e7-9689-56557dc86a2f.png)

MAX: 2016;

![image](https://user-images.githubusercontent.com/5754735/29267989-9595e684-811d-11e7-98d4-54ae2ee35bcb.png)

**Comment by dakkiboy17** [comment]
![image](https://user-images.githubusercontent.com/28706075/29347928-80e5d030-8282-11e7-93b0-9848bb46d134.png)

Nagload ako ng data sa 185 na db. yun ang laman ng current
